# pre-commit
# Ref: https://pre-commit.com/#usage
# ------------------------------------------------------------------------------

# Ref: https://pre-commit.ci/#configuration
ci:
  autofix_prs: false
  autoupdate_commit_msg: 'build: update pre-commit hooks'
  autoupdate_schedule: monthly

repos:
  # Ref: https://pre-commit.com/#meta-hooks
- repo: meta
  hooks:
  - id: check-hooks-apply

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: 4380fbb73a154b5f5624794c1c78d9719ccc860f  # frozen: v2.16.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: ccf21790019848af3eb4464be2a9d5efed6358f3  # frozen: 0.36.1
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/hukkin/mdformat
  rev: 2d496dbc18e31b83a1596685347ffe0b6041daf0  # frozen: 1.0.0
  hooks:
  - id: mdformat
    args: [--wrap=120]
    exclude: .github/PULL_REQUEST_TEMPLATE.md

- repo: https://github.com/crate-ci/typos
  rev: 672d45b4e77223b8fcf1b4b8560bf987f0839902  # frozen: v1
  hooks:
  - id: typos
    args: [--force-exclude]

- repo: local
  hooks:
  - id: check-todos
    name: check for todos
    description: Enforce that there are no TODOs left in the code base
    entry: TODO
    language: pygrep
    types: [text]
    exclude: .pre-commit-config.yaml
