# pre-commit
# Ref: https://pre-commit.com/#usage
# ------------------------------------------------------------------------------

# Ref: https://pre-commit.ci/#configuration
ci:
  autofix_prs: false
  autoupdate_commit_msg: 'build: update pre-commit hooks'
  autoupdate_schedule: monthly

repos:
  # Ref: https://pre-commit.com/#meta-hooks
- repo: meta
  hooks:
  - id: check-hooks-apply

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: a6273196190bb0f68caf1dc68073cf62c719f725  # frozen: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: a20fe80ebdd4aec6791598c9ff559985580f91ea  # frozen: 0.31.1
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/executablebooks/mdformat
  rev: ff29be1a1ba8029d9375882aa2c812b62112a593  # frozen: 0.7.22
  hooks:
  - id: mdformat
    args: [--wrap=120]
    exclude: .github/PULL_REQUEST_TEMPLATE.md

- repo: https://github.com/crate-ci/typos
  rev: e59f226fadcb05a1440bd8b35ee994a9d21bf03b  # frozen: typos-dict-v0.12.4
  hooks:
  - id: typos
    args: [--force-exclude]

- repo: local
  hooks:
  - id: check-todos
    name: check for todos
    description: Enforce that there are no TODOs left in the code base
    entry: TODO
    language: pygrep
    types: [text]
    exclude: .pre-commit-config.yaml
