# pre-commit
# Ref: https://pre-commit.com/#usage
# ------------------------------------------------------------------------------

# Ref: https://pre-commit.ci/#configuration
ci:
  autofix_prs: false
  autoupdate_commit_msg: 'build: update pre-commit hooks'
  autoupdate_schedule: monthly

repos:
  # Ref: https://pre-commit.com/#meta-hooks
- repo: meta
  hooks:
  - id: check-hooks-apply

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: 4380fbb73a154b5f5624794c1c78d9719ccc860f  # frozen: v2.16.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent=2]

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: ed81924a8b1cecdaa570b072528fa80c9c4d6ccd  # frozen: 0.37.1
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/rvben/rumdl-pre-commit
  rev: 916d85f452acfb1f57123538315a130f34fb5a21  # frozen: v0.1.67
  hooks:
  - id: rumdl-fmt
    args:
    - --flavor=gfm    # GitHub Flavored Markdown
    - --disable=MD013 # line length
    exclude: .github/PULL_REQUEST_TEMPLATE.md

- repo: https://github.com/crate-ci/typos
  rev: f06b85043a5ab470afbb0a5592456e733243983a  # frozen: v1
  hooks:
  - id: typos
    args: [--force-exclude]

- repo: local
  hooks:
  - id: check-todos
    name: check for todos
    description: Enforce that there are no TODOs left in the code base
    entry: TODO
    language: pygrep
    types: [text]
    exclude: .pre-commit-config.yaml
