# pre-commit
# Ref: https://pre-commit.com/#usage
# ------------------------------------------------------------------------------

# Ref: https://pre-commit.ci/#configuration
ci:
  autofix_prs: false
  autoupdate_commit_msg: 'build: update pre-commit hooks'
  autoupdate_schedule: monthly

repos:
  # Ref: https://pre-commit.com/#meta-hooks
- repo: meta
  hooks:
  - id: check-hooks-apply

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: a6273196190bb0f68caf1dc68073cf62c719f725  # frozen: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: aa1acdb72677dfbc5f507d2dfd45d8380bbcc2e0  # frozen: 0.29.3
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/executablebooks/mdformat
  rev: 08fba30538869a440b5059de90af03e3502e35fb  # frozen: 0.7.17
  hooks:
  - id: mdformat
    args: [--wrap=120]
    exclude: .github/PULL_REQUEST_TEMPLATE.md

- repo: https://github.com/crate-ci/typos
  rev: 515e0fc2601a0905af8ad0800975c861be1074f1  # frozen: v1.26.0
  hooks:
  - id: typos
    args: [--force-exclude]

- repo: local
  hooks:
  - id: check-todos
    name: check for todos
    description: Enforce that there are no TODOs left in the code base
    entry: TODO
    language: pygrep
    types: [text]
    exclude: .pre-commit-config.yaml
