# pre-commit
# Ref: https://pre-commit.com/#usage
# ------------------------------------------------------------------------------

# Ref: https://pre-commit.ci/#configuration
ci:
  autofix_prs: false
  autoupdate_commit_msg: 'build: update pre-commit hooks'
  autoupdate_schedule: monthly

repos:
  # Ref: https://pre-commit.com/#meta-hooks
- repo: meta
  hooks:
  - id: check-hooks-apply

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: a6273196190bb0f68caf1dc68073cf62c719f725  # frozen: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: e2dde74d0702d15f4f43e4f4fb93e301b4bc1e30  # frozen: 0.29.1
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/executablebooks/mdformat
  rev: 08fba30538869a440b5059de90af03e3502e35fb  # frozen: 0.7.17
  hooks:
  - id: mdformat
    args: [--wrap=120]

- repo: https://github.com/crate-ci/typos
  rev: cc99b94246254c1b3dfa6ea6111aa212b814a486  # frozen: v1.23.6
  hooks:
  - id: typos
    args: [--force-exclude]

- repo: local
  hooks:
  - id: check-todos
    name: check for todos
    description: Enforce that there are no TODOs left in the code base
    entry: TODO
    language: pygrep
    types: [text]
    exclude: .pre-commit-config.yaml
