# This CI job is adapted from:
# build-and-inspect-python-package (2024-03-25), MIT license
# Ref: https://github.com/hynek/build-and-inspect-python-package/blob/v2.2.1/.github/workflows/update-dependencies.yml

# Note: This is a reusable workflow.
#
# Usage: Use the workflow in calling workflows like this:
#   "uses: afuetterer/.github/.github/workflows/_upgrade-requirements.yml@main"
# Pin it to a branch, tag or commit hash.
#
# Ref: https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: Upgrade requirements

on:
  workflow_call:

env:
  UV_EXCLUDE_NEWER: 1 week # ignore packages published in the last week

# Set permissions at the job level.
permissions: {}

jobs:
  upgrade:
    permissions:
      contents: write # for peter-evans/create-pull-request to create branch
      pull-requests: write # for peter-evans/create-pull-request to create a PR
    name: Upgrade requirements
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        python-version: '3.14'
        enable-cache: true
        prune-cache: false
    - run: uv lock --upgrade
      # Ref: https://github.com/peter-evans/create-pull-request
    - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: requirement-upgrades
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        title: 'build(deps): upgrade uv.lock'
        commit-message: 'build(deps): upgrade upgrade uv.lock'
        body: |
          Monthly scheduled upgrade of uv.lock (`uv lock --upgrade`).

          > [!NOTE]
          > Mark this PR as "ready for review" to trigger additional checks.
        add-paths: |
          uv.lock
        labels: |
          type: build
          deps: python
        delete-branch: true
        draft: true
